version: '3'
services:
  wordpress:
    image: instrutordocker/dexter-wordpress
    links:
      - dbserver:instrutordocker/dexter-dbserver
    ports:
      - 80:80
    volumes:
      - $PWD/html:/var/www/html
    restart: always
  dbserver:
    image: instrutordocker/dexter-dbserver
    environment:
      MYSQL_ROOT_PASSWORD: 4linux
    ports:
      - 3306:3306
    volumes:
      - $PWD/banco:/var/lib/mysql
    restart: always
